name: Reporte um Bug
description: Envie um relatório de bug.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - cayo-rodrigues
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por tirar tempo para relatar um bug!

  - type: input
    id: contact
    attributes:
      label: Contato
      description: Como nós podemos entrar em contato com você se precisarmos de mais informações?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: |
        Por favor, também nos diga o que você esperava que acontecesse.
        Você pode incluir imagens/vídeos arrastando-os para este campo.
    validations:
      required: true

  - type: input
    id: when-happened
    attributes:
      label: Quando aconteceu?
      description: |
        Tente se lembrar pelo menos do dia.
      placeholder: 01/01/2000
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Como reproduzir o erro?
      description: Descreva de forma lógica os passos para reproduzir o problema.
      placeholder: |
          1. Acessar a página "frutas",
          2. Digitar "abacaxi" no campo "maçã",
          3. Voltar à página anterior
          4. Os ícones somem
          5. Ao apertar F5 eles reaparecem normalmente
    validations:
      required: false

  - type: checkboxes
    id: browsers
    attributes:
      label: Em quais navegadores o bug acontece?
      options:
        - label: Firefox
          required: false
        - label: Chrome
          required: false
        - label: Safari
          required: false
        - label: Microsoft Edge
          required: false
        - label: Opera
          required: false
        - label: Outros
          required: false
