FROM golang:1.22

RUN apt update -y && \
    apt upgrade -y

WORKDIR /home/app

RUN go install github.com/cosmtrek/air@latest && \
    go install github.com/a-h/templ/cmd/templ@latest

COPY . .

RUN go mod vendor

CMD [ "air" ]
