FROM ubuntu:23.04

WORKDIR /app

RUN apt update -y && \
    apt install -y wget locales unzip

RUN locale-gen pt_BR.UTF-8
ENV LC_ALL pt_BR.UTF-8
ENV LANG pt_BR.UTF-8

RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.198-1_amd64.deb \
    && wget --no-verbose -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip \
    && apt install -y /tmp/chrome.deb \
    && rm /tmp/chrome.deb \
    && unzip /tmp/chromedriver.zip -d /opt/

RUN apt update -y && apt install -y python3-pip python3.11-venv

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD python3 tests.py
