version: '3'

services:
  ss-api:
    container_name: ss-api
    environment:
      - PORT=5000
      - AWS_ACCESS_KEY_ID=''
      - AWS_SECRET_ACCESS_KEY=''
      - AWS_S3_BUCKET_NAME=nff-pdfs
    ports:
      - 5000:5000
    tty: true
    build: .
    volumes:
      - ./:/app
