local_dev_environment:
	curl -Lo "chromedriver-linux64.zip" "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chromedriver-linux64.zip"
		curl -Lo "chrome-linux64.zip" "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chrome-linux64.zip"
		unzip chromedriver-linux64.zip
		unzip chrome-linux64.zip
		export HEADLESS_CHROMIUM_PATH=chrome-linux64/chrome

