name: nff_ss_api_build_and_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop # TEMP!
    paths:
      - "ss-api/**"
      - ".github/workflows/nff_ss_api_build_and_deploy.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.SS_API_AWS_REGION }} 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ss-api/

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        working-directory: ./ss-api
        run: python -m pip install -r requirements.txt

      - name: Deploy to AWS Lambda
        uses: serverless/github-action@v3.2
        with:
          args: deploy
