name: nff_ss_api_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop # TEMP!
    paths:
      - "ss-api/**"
      - ".github/workflows/nff_ss_api_deploy.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ss-api/

      - name: Deploy to AWS Lambda
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./ss-api && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_REGION: ${{ secrets.SS_API_AWS_REGION }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.SS_API_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SS_API_AWS_SECRET_ACCESS_KEY }}
