name: nff_web_build_and_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop # TEMP!
    paths:
      - "web/**"
      - ".github/workflows/nff_web_build_and_deploy.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEB_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd:${{ github.sha }}
      MIGRATIONS_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd-goose:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push image to Docker Hub
        working-directory: ./web
        run: |
          docker build -t $WEB_IMAGE_TAG .
          docker build -t $MIGRATIONS_IMAGE_TAG .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $WEB_IMAGE_TAG
          docker push $MIGRATIONS_IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      WEB_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd:${{ github.sha }}
      MIGRATIONS_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd-goose:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to EC2 instance and deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.EC2_SSH_HOST }}
            USER_NAME: ${{ secrets.EC2_USER_NAME }}
        run: |
          echo $PRIVATE_KEY > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            echo 'LS' && ls -a &&
            cd /home/ubuntu &&
            echo 'LS AGAIN' && ls -a &&
            sudo docker pull \"$WEB_IMAGE_TAG\" &&
            sudo docker pull \"$MIGRATIONS_IMAGE_TAG\" &&
            sudo docker compose up --build migrations &&
            sudo docker compose down web &&
            sudo docker compose up --build web &&
          "
