name: nff_web_build_and_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop # TEMP!
    paths:
      - "web/**"
      - ".github/workflows/nff_web_build_and_deploy.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEB_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd:${{ github.sha }}
      MIGRATIONS_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd-goose:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build images
        working-directory: ./web
        run: |
          docker build -t $WEB_IMAGE_TAG .
          docker build -t $MIGRATIONS_IMAGE_TAG -f Dockerfile.goose .

      - name: Push images to Docker Hub
        run: |
          docker push $WEB_IMAGE_TAG
          docker push $MIGRATIONS_IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      WEB_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd:${{ github.sha }}
      MIGRATIONS_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd-goose:${{ github.sha }}
      PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      HOSTNAME: ${{ secrets.EC2_SSH_HOST }}
      USER_NAME: ${{ secrets.EC2_USER_NAME }}
    steps:
      - name: Set up SSH
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Connect to EC2 instance and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} "
            sudo docker rmi $(sudo docker image ls -q) --force &&
            ./gen-compose.sh \"$WEB_IMAGE_TAG\" \"$MIGRATIONS_IMAGE_TAG\" &&
            sudo udo docker rmi $(sudo docker image ls -q) --forcedocker pull \"$WEB_IMAGE_TAG\" &&
            sudo docker pull \"$MIGRATIONS_IMAGE_TAG\" &&
            sudo docker compose up --build migrations &&
            sudo docker compose down web &&
            sudo docker compose up --build -d web
          "

      - name: Clean up private key
        run: rm private_key.pem
