name: nff_web_build_and_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop # TEMP!
    paths:
      - "web/**"
      - ".github/workflows/nff_web_build_and_deploy.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEB_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd:${{ github.sha }}
      MIGRATIONS_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd-goose:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push image to Docker Hub
        working-directory: ./web
        run: |
          docker build -t $WEB_IMAGE_TAG .
          docker build -t $MIGRATIONS_IMAGE_TAG .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $WEB_IMAGE_TAG
          docker push $MIGRATIONS_IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      WEB_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd:${{ github.sha }}
      MIGRATIONS_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd-goose:${{ github.sha }}
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Connect to EC2 instance and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -l ubuntu ubuntu@ec2-18-230-92-247.sa-east-1.compute.amazonaws.com
          sudo docker pull $WEB_IMAGE_TAG
          sudo docker pull $MIGRATIONS_IMAGE_TAG
          whoami
          pwd
          echo "FIRST LS" && ls -a
          su - ubuntu
          whoami
          pwd
          echo "SECOND LS" && ls -a
          cd /home/ubuntu
          pwd
          echo "THIRD LS" && ls -a
          ls -a
          sudo docker compose up --build migrations
          sudo docker compose down web
          sudo docker compose up --build web
