name: nff_web_build_and_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop # TEMP!
    paths:
      - "web/**"
      - ".github/workflows/nff_web_build_and_deploy.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEB_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd:${{ github.sha }}
      MIGRATIONS_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd-goose:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push image to Docker Hub
        working-directory: ./web
        run: |
          docker build -t $WEB_IMAGE_TAG .
          docker build -t $MIGRATIONS_IMAGE_TAG .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $WEB_IMAGE_TAG
          docker push $MIGRATIONS_IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      WEB_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd:${{ github.sha }}
      MIGRATIONS_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/nff-web-prd-goose:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        working-directory: ./web
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ./nff-key-pair.pem
          chmod 600 ./nff-key-pair.pem

      - name: Copy docker-compose-prd.yaml into EC2 instance
        working-directory: ./web
        run: scp -i ./nff-key-pair.pem -o StrictHostKeyChecking=no ./docker-compose-prd.yaml ubuntu@ec2-18-230-92-247.sa-east-1.compute.amazonaws.com:/home/runner/work/nff/nff

      - name: Connect to EC2 instance
        working-directory: ./web
        run: ssh -o StrictHostKeyChecking=no -i ./nff-key-pair.pem ubuntu@ec2-18-230-92-247.sa-east-1.compute.amazonaws.com

      - name: Deploy
        run: |
          sudo docker pull $WEB_IMAGE_TAG
          sudo docker pull $MIGRATIONS_IMAGE_TAG
          whoami
          pwd
          echo "LS" && ls -a
          sudo docker compose -f ./docker-compose-prd.yaml up --build migrations
          sudo docker compose -f ./docker-compose-prd.yaml down web
          sudo docker compose -f ./docker-compose-prd.yaml up --build web
