services:
  web:
    container_name: nff-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=8080
      - REDIS_URL=redis://rdb:6379/0
      - START_FRESH=true
      - SS_API_BASE_URL=https://bmabg5gxpykclea3u3roxajlxm0kywgy.lambda-url.sa-east-1.on.aws
      - TZ=America/Sao_Paulo
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - rdb

  rdb:
    container_name: nff-rdb
    image: redis:latest
    ports:
      - 6378:6379
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  redis_data:

