FROM golang:1.23

RUN apt update -y && \
    apt upgrade -y

WORKDIR /app

RUN go install github.com/air-verse/air@latest && \
    go install github.com/a-h/templ/cmd/templ@v0.2.707

COPY . .

RUN templ generate && go mod tidy && go mod vendor

CMD [ "air" ]
