version: '3'

services:
  web:
    container_name: nff-web
    image: cayy/nff-web-prd
    environment:
      - PORT=8080
      - DB_URL=postgres://nff:nff@db:5432/nff
      - REDIS_URL=redis://rdb:6379/0
      - SS_API_BASE_URL=https://nff-ss-api-dev.up.railway.app
    ports:
      - 8080:8080
      - 80:8080
    volumes:
      - ./:/home/app
    depends_on:
      - db
      - rdb

  db:
    container_name: nff-db
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=nff
      - POSTGRES_PASSWORD=nff
      - POSTGRES_DB=nff
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rdb:
    container_name: nff-rdb
    image: redis:latest
    ports:
      - 6378:6379
    volumes:
      - redis_data:/var/lib/redis/data

  migrations:
    container_name: nff-migrations
    image: cayy/nff-web-prd-goose
    environment:
      - DB_URL=postgres://nff:nff@db:5432/nff
      - COMMAND=up
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data:


